### ISSUE TITLE
termv stopped working - change in iptv json format 

### ISSUE THREAD

**Issue by Ved-un** [Roshan-R/termv#35] opened 2023-01-21 17:16 UTC
Thank you so much for your project! 

But today my **termv** stopped working for some reason.
I clicked on the link https://iptv-org.github.io/iptv/channels.json and this page does not exist.
They have this https://iptv-org.github.io/api/channels.json - I tried pasting this address but **termv** still doesn't work.

Did they change something or am I having a malfunction?

**Comment by Roshan-R** [comment] 2023-01-22 05:58
It looks like iptv-org has changed the format of the underlying json. 
Looks like we have to change some of the json parsing for it to work.

**Comment by Roshan-R** [comment] 2023-01-22 06:16
as a temporary solution, you could export the environment variable TERMV_API_URL to point to a backup of the old json I have made and continue using termv. To do this - 

1. Export TERMV_API_URL to https://gist.githubusercontent.com/Roshan-R/96c859fc551527284531f59fb52f18df/raw/8c7769a13484111d98339359472174f6ae6ac889/gistfile1.txt
2. run `termv - u`
3. Enjoy

**Comment by Roshan-R** [comment] 2023-01-22 06:17
The changes to the json structure is pretty big for a quick fix. I suppose it would take some time to come up with a solution

**Comment by Ved-un** [comment] 2023-01-22 09:14
I don't have a backup of json.
Alright, I'll use pure mpv and my iptv playlists for now.

**Comment by timsofteng** [comment] 2023-03-02 09:34
@Roshan-R dtill doesn't work automatically...
And a lot of channels from your bellow tip don't work.
May you please provide updated link or fix it?
Thanks

**Comment by Roshan-R** [comment] 2023-03-07 18:09
I have implemented a fix for this issue into a new branch named `fix`.
Could you check if it's working or not?

**Comment by divcyb** [comment] 2023-03-09 09:01
It kinda works thank you, but some channels error out like this
`Fetching channel, please wait...
[file] Cannot open file '': No such file or directory
Failed to open .`

**Comment by odnar-dev** [comment] 2023-03-12 11:15
hi @Roshan-R ,
why not move the filtering to the update function?
instead of just downloading both files and storing them in their original format, you can process them (merge both files into one, remove channels without url...)

we can also create a json schema specific to termv (easy to read, and easy to reproduce if the user wants to create his own channel list).

**Comment by Roshan-R** [comment] 2023-03-14 04:51
That seems like a great idea @odnar-dev, I too was thinking of making something like this.

1. What all should be included into the json schema? I feel like we should only store the data that we really want and that would be name, categories, languages and the url.
2. I'm also curious about the speed of processing this data

**Comment by Roshan-R** [comment] 2023-03-14 14:27
I have updated the `fix` branch having implemented the idea suggested by @odnar-dev, the two json files are merged into a single one in the update function.
This also fixes the issue raised by @divcyb about showing channels which do not have any urls pointed to it

**Comment by odnar-dev** [comment] 2023-03-14 14:34
:laughing:  i was about to suggest 

![image](https://user-images.githubusercontent.com/73726132/225033950-e762a188-482a-48a3-98b6-925b42f4c06e.png)

**Comment by Roshan-R** [comment] 2023-03-19 07:04
I guess we could merge the `fix` branch with the `main` branch?

**Comment by sekret1** [comment] 2023-03-26 20:57
I'd vote for "not yet":

`$ termv
parse error: Invalid numeric literal at line 1, column 10`

I've run the latest version from fix / main
`$ termv -v
termv 1.4`

**Comment by Roshan-R** [comment] 2023-03-27 04:08
@sekret1 I have added a new commit to the `fix` branch, could you see if it works now?

**Closed** 2023-06-18 05:45 UTC
